
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = xilkernel
 PARAMETER OS_VER = 4.00.a
 PARAMETER PROC_INSTANCE = ppc405_0
 PARAMETER sysintc_spec = xps_intc_0
 PARAMETER stdout = RS232
 PARAMETER stdin = RS232
 PARAMETER debug_mon = true
 PARAMETER enhanced_features = true
 PARAMETER config_yield = true
 PARAMETER config_kill = true
 PARAMETER config_msgq = true
 PARAMETER config_sema = true
 PARAMETER config_named_sema = true
 PARAMETER config_time = true
 PARAMETER use_malloc = true
 PARAMETER pthread_stack_size = 32768
 PARAMETER msgq_capacity = 100
 PARAMETER num_msgqs = 100
 PARAMETER max_sem_waitq = 100
 PARAMETER max_sem = 100
 PARAMETER max_tmrs = 100
 PARAMETER max_pthreads = 100
 PARAMETER config_pthread_mutex = true
 PARAMETER systmr_interval = 1
 PARAMETER sched_type = SCHED_PRIO
 PARAMETER max_readyq = 100
 PARAMETER max_pthread_mutex_waitq = 100
 PARAMETER max_pthread_mutex = 100
 PARAMETER static_pthread_table = ((main_thread,3))
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_ppc405
 PARAMETER DRIVER_VER = 1.10.b
 PARAMETER HW_INSTANCE = ppc405_0
 PARAMETER COMPILER = powerpc-eabi-gcc
 PARAMETER ARCHIVER = powerpc-eabi-ar
 PARAMETER CORE_CLOCK_FREQ_HZ = 100000000
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = jtagppc_cntlr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = xps_bram_if_cntlr_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = plb_bram_if_cntlr_1_bram
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 2.12.a
 PARAMETER HW_INSTANCE = LEDS
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mpmc
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = SDR_SDRAM_CUSTOM
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = clock_generator_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = proc_sys_reset_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 1.11.a
 PARAMETER HW_INSTANCE = xps_intc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = xps_spi_sd
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = xps_spi_max
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = xps_spi_osram
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 1.13.a
 PARAMETER HW_INSTANCE = RS232
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 1.13.a
 PARAMETER HW_INSTANCE = RS485
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = motion
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = motion_x
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = motion
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = motion_y
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = motion
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = motion_z
END


